[tools]
1password = "latest"
java = "21"
pnpm = "10"

[tasks.compile]
run = "javac me/fabianmoronzirfas/lox/Lox.java"

[tasks.compile-tools]
run = "javac me/fabianmoronzirfas/tool/GenerateAst.java"

[tasks.run-generate-ast]
run = "java me.fabianmoronzirfas.tool.GenerateAst me/fabianmoronzirfas/lox/"
